name: ChadTreeCapitator
version: '${version}'
main: me.reno.treecapitator.TreeCapitator
api-version: '1.21'
author: reno
description: Chop the whole tree at once with the Chad Axe.

commands:
  chadaxe:
    description: Gives you the Chad Axe.
    usage: /chadaxe
    permission: treecapitator.give

permissions:
  treecapitator.give:
    description: Allows giving yourself the Chad Axe.
    default: op