name: ChadTreeCapitator
version: '1.0.0'
main: me.reno.treecapitator.TreeCapitatorPlugin
api-version: '26.1.2'
description: Chad Tree Capitator

permissions:
  treecapitator.chad:
    description: Allows the player to use /chad
    default: true
